<?php
/**
 * Created by PhpStorm.
 * User: miunh
 * Date: 03-Aug-16
 * Time: 9:48 PM
 */
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Class Image_home
 */
class Image_home extends Manager_base {
    public function __construct() {
        parent::__construct();
    }

    public function setting_class() {
        // TODO: Implement setting_class() method.
        $this->name = Array(
            "class"  => "admin/image_home",
            "view"   => "image_home",
            "model"  => "m_image_homes",
            "object" => "hình ảnh",
        );
    }

    public function manager($data = Array()) {
        $data['view_file'] = 'admin/user_base_manager/manager_container';
        parent::manager($data); // TODO: Change the autogenerated stub
    }

    public function add_action_button($origin_column_value, $column_name, &$record, $column_data, $caller) {
        $primary_key = $this->model->get_primary_key();
        $custom_action = "<div class='action-buttons'>";
        if ((!isset($record->disable_edit) || !$record->disable_edit)) {
            $custom_action .= "<a class='e_ajax_link green' href='" . site_url($this->url["edit"] . $record->$primary_key) . "'><i class='ace-icon fa fa-pencil bigger-130'></i></a>";
        }
        $custom_action .= "</div>";
        return $custom_action;
    }
}